# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'My Browser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My Browser
pod 'Google-Mobile-Ads-SDK'	
end
